### GET /
### get the web page
GET http://localhost:3000


### POST /auth/login
### login the existing user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "devinder@mail.com",
    "password": "hello@123"
}


### POST /auth/register
### register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "devinder@mail.com",
    "password": "hello@123"
}


### GET /todos
### get all todos (auth required)
GET http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ0NTU3LCJleHAiOjE3NTMwMzA5NTd9.uXrX_hjAq2uBn9ekOsE_-jlfgd49wTl_Okn_9mHLIrM


### POST /todos
### create a new todo (auth required)
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ0NTU3LCJleHAiOjE3NTMwMzA5NTd9.uXrX_hjAq2uBn9ekOsE_-jlfgd49wTl_Okn_9mHLIrM

{
    "task": "Finish backend project"
}


### PUT /todos/:id
### update a todo (auth required)
PUT http://localhost:3000/todos/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ0NTU3LCJleHAiOjE3NTMwMzA5NTd9.uXrX_hjAq2uBn9ekOsE_-jlfgd49wTl_Okn_9mHLIrM

{
    "task": "Finish backend project (updated)",
    "completed": true
}


### DELETE /todos/:id
### delete a todo (auth required)
DELETE http://localhost:3000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ0NTU3LCJleHAiOjE3NTMwMzA5NTd9.uXrX_hjAq2uBn9ekOsE_-jlfgd49wTl_Okn_9mHLIrM
